#!/usr/bin/env python

import sys
import subprocess

def usage():
  print "usage: qarg <cmd>"

def q(s):
  return '"' + s + '"'

def go(cmd):
  data = sys.stdin.read()
  cmd.append(data)
  subprocess.call(cmd)

cmd = sys.argv[1:]
if len(cmd) == 0:
  usage()
else:
  go(cmd)

